# Generated by Django 5.0.2 on 2024-02-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='erm',
            field=models.BooleanField(default=False),
        ),
    ]
